//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class BovedaMovimiento
    {
        public int Id { get; set; }
        public int BovedaId { get; set; }
        public Nullable<int> CajaDiarioId { get; set; }
        public int OperacionId { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Glosa { get; set; }
        public decimal Importe { get; set; }
    
        public virtual Boveda Boveda { get; set; }
        public virtual CajaDiario CajaDiario { get; set; }
        public virtual Operacion Operacion { get; set; }
    }
}
