//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CajaMovimiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CajaMovimiento()
        {
            this.CajaMovimientoDetalle = new HashSet<CajaMovimientoDetalle>();
        }
    
        public int Id { get; set; }
        public int CajaDiarioId { get; set; }
        public Nullable<int> AlumnoId { get; set; }
        public Nullable<int> PersonalId { get; set; }
        public int OperacionId { get; set; }
        public int EstadoId { get; set; }
        public string Serie { get; set; }
        public string Numero { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<decimal> Total { get; set; }
        public bool IndEntrada { get; set; }
        public string Descripcion { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual CajaDiario CajaDiario { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Operacion Operacion { get; set; }
        public virtual Personal Personal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CajaMovimientoDetalle> CajaMovimientoDetalle { get; set; }
    }
}
