//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CajaDiario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CajaDiario()
        {
            this.BovedaMovimiento = new HashSet<BovedaMovimiento>();
            this.CajaMovimiento = new HashSet<CajaMovimiento>();
        }
    
        public int Id { get; set; }
        public int CajaId { get; set; }
        public int UsuarioId { get; set; }
        public decimal SaldoInicial { get; set; }
        public Nullable<decimal> Entradas { get; set; }
        public Nullable<decimal> Salidas { get; set; }
        public Nullable<decimal> SaldoFinal { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public bool IndCierre { get; set; }
        public bool IndBoveda { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BovedaMovimiento> BovedaMovimiento { get; set; }
        public virtual Caja Caja { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CajaMovimiento> CajaMovimiento { get; set; }
    }
}
