//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentasPorCobrar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CuentasPorCobrar()
        {
            this.CuentasPorCobrarDetalle = new HashSet<CuentasPorCobrarDetalle>();
        }
    
        public int Id { get; set; }
        public Nullable<int> MatriculaId { get; set; }
        public int EstadoId { get; set; }
        public int AlumnoId { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Total { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> CajaMovimientoId { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
    
        public virtual Estado Estado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CuentasPorCobrarDetalle> CuentasPorCobrarDetalle { get; set; }
        public virtual Matricula Matricula { get; set; }
        public virtual Alumno Alumno { get; set; }
    }
}
