//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Horario
    {
        public int Id { get; set; }
        public int PeriodoId { get; set; }
        public int CursoId { get; set; }
        public Nullable<int> AulaId { get; set; }
        public int Hora { get; set; }
        public int CantidadHora { get; set; }
        public int Dia { get; set; }
    
        public virtual Aula Aula { get; set; }
        public virtual Periodo Periodo { get; set; }
        public virtual Curso Curso { get; set; }
    }
}
