//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatriculaDetalle
    {
        public int Id { get; set; }
        public int MatriculaId { get; set; }
        public int CursoId { get; set; }
    
        public virtual Matricula Matricula { get; set; }
        public virtual Curso Curso { get; set; }
    }
}
