//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personal_Tipo
    {
        public int Id { get; set; }
        public int PersonalId { get; set; }
        public int TipoPersonalId { get; set; }
    
        public virtual Personal Personal { get; set; }
        public virtual TipoPersonal TipoPersonal { get; set; }
    }
}
